spring.application.name=server
# ???? ?? <password> ?????? ?????? ???? (tkhumuphv1)
#spring.data.mongodb.uri=mongodb://Tzofia:tkhumuphv1@stegnografydb.pxvxq0c.mongodb.net:27017/StegaShare?authSource=admin&retryWrites=true&w=majority
spring.data.mongodb.uri=mongodb+srv://Tzofia:tkhumuphv1@stegnografydb.pxvxq0c.mongodb.net/StegaShare?retryWrites=true&w=majority&appName=StegnografyDB
# ?? ?-Database ????? ?? ?????????
spring.data.mongodb.database=StegaShare

# ????? ????? ???????? ????? ???? (???? 50 ???)
spring.servlet.multipart.max-file-size=1000MB

# ????? ??? ?????? ?-30 ?????
spring.data.mongodb.connect-timeout=30000 
# ????? ??? ??????? ???? (60 ?????)
spring.data.mongodb.socket-timeout=60000
# ????? ???? ??????? ???????? (???? 50)
spring.data.mongodb.min-connections-per-host=5
spring.data.mongodb.max-connections-per-host=50
